version: '2'

services:
  api:
    build: api/
    volumes:
      - './api/:/usr/local/opt/apps'
    environment:
      VIRTUAL_HOST: 'vanels.dev'
    #command: php -S 0.0.0.0:80 -t public/ public/index.php
    command: tail -f /dev/null
  lb:
    image: 'dockercloud/haproxy:1.5.3'
    links:
      - api
    environment:
      STATS_AUTH: 'devlusaja:123456'
      STATS_PORT: '1936'
      MONITOR_PORT: '80'
      MONITOR_URI: '/status'
    ports:
      - '1936:1936'
      - '8080:80'
    depends_on:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock